/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.cindi.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        cindi.java.Library classUnderTest = new cindi.java.Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
